<?php
# If the form request method is POST, process it to the server by connecting to the connect_db.php database:
    if ($_SERVER['REQUEST_METHOD'] == 'POST') {
        # Connect to the database:
        require('connect_db.php');

        # Initialise an error array in case we need it:
        $errors = array();

        # Check for an item id: if it is empty, log an error into the errors array:
        if (empty($_POST['item_id'])) {
            $errors[] = 'Update item ID';
        } else {
            $id = mysqli_real_escape_string($link, trim($_POST['item_id']));
        }

        # Check for an item name: 
        if (empty($_POST['item_name'])) {
            $errors[] = 'Update item name';
        } else {
            $n = mysqli_real_escape_string($link, trim($_POST['item_name']));
        }

        # Check for an item description:
        if (empty($_POST['item_desc'])) {
            $errors[] = 'Update item description';
        } else {
            $d = mysqli_real_escape_string($link, trim($_POST['item_desc']));
        }

        # Check for an item image:
        if (empty($_POST['item_img'])) {
            $errors[] = 'Update item image';
        } else {
            $i = mysqli_real_escape_string($link, trim($_POST['item_img']));
        }

        # Check for an item price:
        if (empty($_POST['item_price'])) {
            $errors[] = 'Update item price';
        } else {
            $p = mysqli_real_escape_string($link, trim($_POST['item_price']));
        }

        # If there are no errors, run the code:
        if (empty($errors)) {
            $q = "UPDATE products SET item_id='$id', item_name='$n', item_desc='$d', item_img='$i', item_price='$p' WHERE item_id='$id'";
            # $q = Update the products table, specify the columns you want to update and the new values. Each variable here contains the values you want to update the columns with.
            # WHERE - Specifies which records to update (in this case, only the record item_id with the value $id is updated)

            $r = @mysqli_query($link, $q); # Query to execute $q on the $link database
            
            if ($r) { # If the query is successful, aka $r is not false...
                header("Location: read.php"); # The user is redirected to read.php page
            } else {
                echo "Error updating record: " . $link->error; # else print an error message generated by MySQL.
            }
        }

        # If there are errors, display them: 

         if (!empty($errors)) {
             echo '<div class="error-messages">';
                foreach ($errors as $error) {
                 echo '<p>' . $error . '</p>';
                }
            echo '</div>';
        }

        # Close database connection:
        mysqli_close($link);
        exit();
    }

?>

<!-- HTML Update Form -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Update Form</title>
    </head>
    <body>
        <form action="update.php" method="POST">
            <label for="item_id">Update the item ID</label>
            <input type="text" name="item_id"
            value="<?php if (isset($_POST['item_id'])) echo $_POST['item_id']; ?>"> 
            <br>
            <label for="item_name">Update Item Name</label>
            <input type="text" name="item_name" value="<?php if (isset($_POST['item_name'])) echo $_POST['item_name']; ?>"> 
            <!-- value: initial value - checks whether the form has been set to send by POST.
             If it is, it populated the input field with the data from $_POST['item_name] -->
            <br>
            <label for="item_desc">Update Item Description</label>
            <input type="text" name="item_desc" value="<?php if (isset($_POST['item_desc'])) echo $_POST['item_desc']; ?>">
            <br>
            <label for="item_img">Update Item Image</label>
            <input type="text" name="item_img" value="<?php if (isset($_POST['item_img'])) echo $_POST['item_img']; ?>">
            <br>
            <label for="item_desc">Update Item Price</label>
            <input type="text" name="item_price" value="<?php if (isset($_POST['item_price'])) echo $_POST['item_price']; ?>">
            <br>
            <input type="submit" value="Update Record"></p>
        </form>
        <br>
   <a href="create.php">Add Records</a>  |  <a href="read.php">Read Records</a>  |  <a href="update.php">Update Record</a>  | <a href="delete.php">Delete Record</a>
</form>
</body>

</html>